package jp.ac.titech.cs.sa.tklab.faultlocalize.bxmodelutil;

/**
 * 
 * @author ?
 *
 */
public enum NodeKind {
	METHOD_ENTRY,
	METHOD_EXIT,
	CONSTRUCTOR_ENTRY,
	CONSTRUCTOR_EXIT,
	CONDITION_START,
	CONDITION_END,
	LOOP_START,
	LOOPING,
	LOOP_END,
	ITERATION_START,
	ITERATION_END,
	TRY_START,
	TRY_END,
	CATCH_START,
	CATCH_END,
	FINALLY_START,
	FINALLY_END,
	VARIABLE_DEFINITION,
	VARIABLE_REFERENCE,
	EXCEPTION_OCCURRENCE,
	DUMMY
}